using System.Collections.Generic;

namespace Backoffice.Services
{
    public class Country
    {
        public Country(string key, string value)
        {
            Code = key;
            Name = value;
        }
        public string Code { get; set; }
        public string Name { get; set; }
    }
    
    public static class CountryManager
    {
        #region EnglishNames
        private static readonly Dictionary<string, string> EnglishNames = new Dictionary<string, string>
        {
            {"ABW", "Aruba"},
            {"AFG", "Afghanistan"},
            {"AGO", "Angola"},
            {"AIA", "Anguilla"},
            {"ALA", "Åland Islands"},
            {"ALB", "Albania"},
            {"AND", "Andorra"},
            {"ARE", "United Arab Emirates"},
            {"ARG", "Argentina"},
            {"ARM", "Armenia"},
            {"ASM", "American Samoa"},
            {"ATA", "Antarctica"},
            {"ATF", "French Southern Territories"},
            {"ATG", "Antigua and Barbuda"},
            {"AUS", "Australia"},
            {"AUT", "Austria"},
            {"AZE", "Azerbaijan"},
            {"BDI", "Burundi"},
            {"BEL", "Belgium"},
            {"BEN", "Benin"},
            {"BES", "Bonaire, Sint Eustatius and Saba"},
            {"BFA", "Burkina Faso"},
            {"BGD", "Bangladesh"},
            {"BGR", "Bulgaria"},
            {"BHR", "Bahrain"},
            {"BHS", "Bahamas"},
            {"BIH", "Bosnia and Herzegovina"},
            {"BLM", "Saint Barthélemy"},
            {"BLR", "Belarus"},
            {"BLZ", "Belize"},
            {"BMU", "Bermuda"},
            {"BOL", "Bolivia, Plurinational State of"},
            {"BRA", "Brazil"},
            {"BRB", "Barbados"},
            {"BRN", "Brunei Darussalam"},
            {"BTN", "Bhutan"},
            {"BVT", "Bouvet Island"},
            {"BWA", "Botswana"},
            {"CAF", "Central African Republic"},
            {"CAN", "Canada"},
            {"CCK", "Cocos (Keeling) Islands"},
            {"CHE", "Switzerland"},
            {"CHL", "Chile"},
            {"CHN", "China"},
            {"CIV", "Côte d'Ivoire"},
            {"CMR", "Cameroon"},
            {"COD", "Congo, the Democratic Republic of the"},
            {"COG", "Congo"},
            {"COK", "Cook Islands"},
            {"COL", "Colombia"},
            {"COM", "Comoros"},
            {"CPV", "Cabo Verde"},
            {"CRI", "Costa Rica"},
            {"CUB", "Cuba"},
            {"CUW", "Curaçao"},
            {"CXR", "Christmas Island"},
            {"CYM", "Cayman Islands"},
            {"CYP", "Cyprus"},
            {"CZE", "Czech Republic"},
            {"DEU", "Germany"},
            {"DJI", "Djibouti"},
            {"DMA", "Dominica"},
            {"DNK", "Denmark"},
            {"DOM", "Dominican Republic"},
            {"DZA", "Algeria"},
            {"ECU", "Ecuador"},
            {"EGY", "Egypt"},
            {"ERI", "Eritrea"},
            {"ESH", "Western Sahara"},
            {"ESP", "Spain"},
            {"EST", "Estonia"},
            {"ETH", "Ethiopia"},
            {"FIN", "Finland"},
            {"FJI", "Fiji"},
            {"FLK", "Falkland Islands (Malvinas)"},
            {"FRA", "France"},
            {"FRO", "Faroe Islands"},
            {"FSM", "Micronesia, Federated States of"},
            {"GAB", "Gabon"},
            {"GBR", "United Kingdom"},
            {"GEO", "Georgia"},
            {"GGY", "Guernsey"},
            {"GHA", "Ghana"},
            {"GIB", "Gibraltar"},
            {"GIN", "Guinea"},
            {"GLP", "Guadeloupe"},
            {"GMB", "Gambia"},
            {"GNB", "Guinea-Bissau"},
            {"GNQ", "Equatorial Guinea"},
            {"GRC", "Greece"},
            {"GRD", "Grenada"},
            {"GRL", "Greenland"},
            {"GTM", "Guatemala"},
            {"GUF", "French Guiana"},
            {"GUM", "Guam"},
            {"GUY", "Guyana"},
            {"HKG", "Hong Kong"},
            {"HMD", "Heard Island and McDonald Islands"},
            {"HND", "Honduras"},
            {"HRV", "Croatia"},
            {"HTI", "Haiti"},
            {"HUN", "Hungary"},
            {"IDN", "Indonesia"},
            {"IMN", "Isle of Man"},
            {"IND", "India"},
            {"IOT", "British Indian Ocean Territory"},
            {"IRL", "Ireland"},
            {"IRN", "Iran, Islamic Republic of"},
            {"IRQ", "Iraq"},
            {"ISL", "Iceland"},
            {"ISR", "Israel"},
            {"ITA", "Italy"},
            {"JAM", "Jamaica"},
            {"JEY", "Jersey"},
            {"JOR", "Jordan"},
            {"JPN", "Japan"},
            {"KAZ", "Kazakhstan"},
            {"KEN", "Kenya"},
            {"KGZ", "Kyrgyzstan"},
            {"KHM", "Cambodia"},
            {"KIR", "Kiribati"},
            {"KNA", "Saint Kitts and Nevis"},
            {"KOR", "Korea, Republic of"},
            {"KWT", "Kuwait"},
            {"LAO", "Lao People's Democratic Republic"},
            {"LBN", "Lebanon"},
            {"LBR", "Liberia"},
            {"LBY", "Libya"},
            {"LCA", "Saint Lucia"},
            {"LIE", "Liechtenstein"},
            {"LKA", "Sri Lanka"},
            {"LSO", "Lesotho"},
            {"LTU", "Lithuania"},
            {"LUX", "Luxembourg"},
            {"LVA", "Latvia"},
            {"MAC", "Macao"},
            {"MAF", "Saint Martin (French part)"},
            {"MAR", "Morocco"},
            {"MCO", "Monaco"},
            {"MDA", "Moldova, Republic of"},
            {"MDG", "Madagascar"},
            {"MDV", "Maldives"},
            {"MEX", "Mexico"},
            {"MHL", "Marshall Islands"},
            {"MKD", "Macedonia, the former Yugoslav Republic of"},
            {"MLI", "Mali"},
            {"MLT", "Malta"},
            {"MMR", "Myanmar"},
            {"MNE", "Montenegro"},
            {"MNG", "Mongolia"},
            {"MNP", "Northern Mariana Islands"},
            {"MOZ", "Mozambique"},
            {"MRT", "Mauritania"},
            {"MSR", "Montserrat"},
            {"MTQ", "Martinique"},
            {"MUS", "Mauritius"},
            {"MWI", "Malawi"},
            {"MYS", "Malaysia"},
            {"MYT", "Mayotte"},
            {"NAM", "Namibia"},
            {"NCL", "New Caledonia"},
            {"NER", "Niger"},
            {"NFK", "Norfolk Island"},
            {"NGA", "Nigeria"},
            {"NIC", "Nicaragua"},
            {"NIU", "Niue"},
            {"NLD", "Netherlands"},
            {"NOR", "Norway"},
            {"NPL", "Nepal"},
            {"NRU", "Nauru"},
            {"NZL", "New Zealand"},
            {"OMN", "Oman"},
            {"PAK", "Pakistan"},
            {"PAN", "Panama"},
            {"PCN", "Pitcairn"},
            {"PER", "Peru"},
            {"PHL", "Philippines"},
            {"PLW", "Palau"},
            {"PNG", "Papua New Guinea"},
            {"POL", "Poland"},
            {"PRI", "Puerto Rico"},
            {"PRK", "Korea, Democratic People's Republic of"},
            {"PRT", "Portugal"},
            {"PRY", "Paraguay"},
            {"PSE", "Palestine, State of"},
            {"PYF", "French Polynesia"},
            {"QAT", "Qatar"},
            {"REU", "Réunion"},
            {"ROU", "Romania"},
            {"RUS", "Russian Federation"},
            {"RWA", "Rwanda"},
            {"SAU", "Saudi Arabia"},
            {"SDN", "Sudan"},
            {"SEN", "Senegal"},
            {"SGP", "Singapore"},
            {"SGS", "South Georgia and the South Sandwich Islands"},
            {"SHN", "Saint Helena, Ascension and Tristan da Cunha"},
            {"SJM", "Svalbard and Jan Mayen"},
            {"SLB", "Solomon Islands"},
            {"SLE", "Sierra Leone"},
            {"SLV", "El Salvador"},
            {"SMR", "San Marino"},
            {"SOM", "Somalia"},
            {"SPM", "Saint Pierre and Miquelon"},
            {"SRB", "Serbia"},
            {"SSD", "South Sudan"},
            {"STP", "Sao Tome and Principe"},
            {"SUR", "Suriname"},
            {"SVK", "Slovakia"},
            {"SVN", "Slovenia"},
            {"SWE", "Sweden"},
            {"SWZ", "Swaziland"},
            {"SXM", "Sint Maarten (Dutch part)"},
            {"SYC", "Seychelles"},
            {"SYR", "Syrian Arab Republic"},
            {"TCA", "Turks and Caicos Islands"},
            {"TCD", "Chad"},
            {"TGO", "Togo"},
            {"THA", "Thailand"},
            {"TJK", "Tajikistan"},
            {"TKL", "Tokelau"},
            {"TKM", "Turkmenistan"},
            {"TLS", "Timor-Leste"},
            {"TON", "Tonga"},
            {"TTO", "Trinidad and Tobago"},
            {"TUN", "Tunisia"},
            {"TUR", "Turkey"},
            {"TUV", "Tuvalu"},
            {"TWN", "Taiwan, Province of China"},
            {"TZA", "Tanzania, United Republic of"},
            {"UGA", "Uganda"},
            {"UKR", "Ukraine"},
            {"UMI", "United States Minor Outlying Islands"},
            {"URY", "Uruguay"},
            {"USA", "United States"},
            {"UZB", "Uzbekistan"},
            {"VAT", "Holy See (Vatican City State)"},
            {"VCT", "Saint Vincent and the Grenadines"},
            {"VEN", "Venezuela, Bolivarian Republic of"},
            {"VGB", "Virgin Islands, British"},
            {"VIR", "Virgin Islands, U.S."},
            {"VNM", "Viet Nam"},
            {"VUT", "Vanuatu"},
            {"WLF", "Wallis and Futuna"},
            {"WSM", "Samoa"},
            {"YEM", "Yemen"},
            {"ZAF", "South Africa"},
            {"ZMB", "Zambia"},
            {"ZWE", "Zimbabwe"},
        };
        #endregion
        #region ISO Codes2To3
        private static readonly Dictionary<string, string> Iso2ToIso3Dict = new Dictionary<string, string>
        {
            {"AB", "ABW"},
            {"AF", "AFG"},
            {"AO", "AGO"},
            {"AI", "AIA"},
            {"AX", "ALA"},
            {"AL", "ALB"},
            {"AD", "AND"},
            {"AE", "ARE"},
            {"AR", "ARG"},
            {"AM", "ARM"},
            {"AS", "ASM"},
            {"AQ", "ATA"},
            {"TF", "ATF"},
            {"AG", "ATG"},
            {"AU", "AUS"},
            {"AT", "AUT"},
            {"AZ", "AZE"},
            {"BI", "BDI"},
            {"BE", "BEL"},
            {"BJ", "BEN"},
            {"BQ", "BES"},
            {"BF", "BFA"},
            {"BD", "BGD"},
            {"BG", "BGR"},
            {"BH", "BHR"},
            {"BS", "BHS"},
            {"BA", "BIH"},
            {"BL", "BLM"},
            {"BY", "BLR"},
            {"BZ", "BLZ"},
            {"BM", "BMU"},
            {"BO", "BOL"},
            {"BR", "BRA"},
            {"BB", "BRB"},
            {"BN", "BRN"},
            {"BT", "BTN"},
            {"BV", "BVT"},
            {"BW", "BWA"},
            {"CF", "CAF"},
            {"CA", "CAN"},
            {"CC", "CCK"},
            {"CH", "CHE"},
            {"CL", "CHL"},
            {"CN", "CHN"},
            {"CI", "CIV"},
            {"CM", "CMR"},
            {"CD", "COD"},
            {"CG", "COG"},
            {"CK", "COK"},
            {"CO", "COL"},
            {"KM", "COM"},
            {"CV", "CPV"},
            {"CR", "CRI"},
            {"CU", "CUB"},
            {"CW", "CUW"},
            {"CX", "CXR"},
            {"KY", "CYM"},
            {"CY", "CYP"},
            {"CZ", "CZE"},
            {"DE", "DEU"},
            {"DJ", "DJI"},
            {"DM", "DMA"},
            {"DK", "DNK"},
            {"DO", "DOM"},
            {"DZ", "DZA"},
            {"EC", "ECU"},
            {"EG", "EGY"},
            {"ER", "ERI"},
            {"EH", "ESH"},
            {"ES", "ESP"},
            {"EE", "EST"},
            {"ET", "ETH"},
            {"FI", "FIN"},
            {"FJ", "FJI"},
            {"FK", "FLK"},
            {"FR", "FRA"},
            {"FO", "FRO"},
            {"FM", "FSM"},
            {"GA", "GAB"},
            {"GB", "GBR"},
            {"GE", "GEO"},
            {"GG", "GGY"},
            {"GH", "GHA"},
            {"GI", "GIB"},
            {"GN", "GIN"},
            {"GP", "GLP"},
            {"GM", "GMB"},
            {"GW", "GNB"},
            {"GQ", "GNQ"},
            {"GR", "GRC"},
            {"GD", "GRD"},
            {"GL", "GRL"},
            {"GT", "GTM"},
            {"GF", "GUF"},
            {"GU", "GUM"},
            {"GY", "GUY"},
            {"HK", "HKG"},
            {"HM", "HMD"},
            {"HN", "HND"},
            {"HR", "HRV"},
            {"HT", "HTI"},
            {"HU", "HUN"},
            {"ID", "IDN"},
            {"IM", "IMN"},
            {"IN", "IND"},
            {"IO", "IOT"},
            {"IE", "IRL"},
            {"IR", "IRN"},
            {"IQ", "IRQ"},
            {"IS", "ISL"},
            {"IL", "ISR"},
            {"IT", "ITA"},
            {"JM", "JAM"},
            {"JE", "JEY"},
            {"JO", "JOR"},
            {"JP", "JPN"},
            {"KZ", "KAZ"},
            {"KE", "KEN"},
            {"KG", "KGZ"},
            {"KH", "KHM"},
            {"KI", "KIR"},
            {"KN", "KNA"},
            {"KR", "KOR"},
            {"KW", "KWT"},
            {"LA", "LAO"},
            {"LB", "LBN"},
            {"LR", "LBR"},
            {"LY", "LBY"},
            {"LC", "LCA"},
            {"LI", "LIE"},
            {"LK", "LKA"},
            {"LS", "LSO"},
            {"LT", "LTU"},
            {"LU", "LUX"},
            {"LV", "LVA"},
            {"MO", "MAC"},
            {"MF", "MAF"},
            {"MA", "MAR"},
            {"MC", "MCO"},
            {"MD", "MDA"},
            {"MG", "MDG"},
            {"MV", "MDV"},
            {"MX", "MEX"},
            {"MH", "MHL"},
            {"MK", "MKD"},
            {"ML", "MLI"},
            {"MT", "MLT"},
            {"MM", "MMR"},
            {"ME", "MNE"},
            {"MN", "MNG"},
            {"MP", "MNP"},
            {"MZ", "MOZ"},
            {"MR", "MRT"},
            {"MS", "MSR"},
            {"MQ", "MTQ"},
            {"MU", "MUS"},
            {"MW", "MWI"},
            {"MY", "MYS"},
            {"YT", "MYT"},
            {"NA", "NAM"},
            {"NC", "NCL"},
            {"NE", "NER"},
            {"NF", "NFK"},
            {"NG", "NGA"},
            {"NI", "NIC"},
            {"NU", "NIU"},
            {"NL", "NLD"},
            {"NO", "NOR"},
            {"NP", "NPL"},
            {"NR", "NRU"},
            {"NZ", "NZL"},
            {"OM", "OMN"},
            {"PK", "PAK"},
            {"PA", "PAN"},
            {"PN", "PCN"},
            {"PE", "PER"},
            {"PH", "PHL"},
            {"PW", "PLW"},
            {"PG", "PNG"},
            {"PL", "POL"},
            {"PR", "PRI"},
            {"KP", "PRK"},
            {"PT", "PRT"},
            {"PY", "PRY"},
            {"PS", "PSE"},
            {"PF", "PYF"},
            {"QA", "QAT"},
            {"RE", "REU"},
            {"RO", "ROU"},
            {"RU", "RUS"},
            {"RW", "RWA"},
            {"SA", "SAU"},
            {"SD", "SDN"},
            {"SN", "SEN"},
            {"SG", "SGP"},
            {"GS", "SGS"},
            {"SH", "SHN"},
            {"SJ", "SJM"},
            {"SB", "SLB"},
            {"SL", "SLE"},
            {"SV", "SLV"},
            {"SM", "SMR"},
            {"SO", "SOM"},
            {"PM", "SPM"},
            {"RS", "SRB"},
            {"SS", "SSD"},
            {"ST", "STP"},
            {"SR", "SUR"},
            {"SK", "SVK"},
            {"SI", "SVN"},
            {"SE", "SWE"},
            {"SZ", "SWZ"},
            {"SX", "SXM"},
            {"SC", "SYC"},
            {"SY", "SYR"},
            {"TC", "TCA"},
            {"TD", "TCD"},
            {"TG", "TGO"},
            {"TH", "THA"},
            {"TJ", "TJK"},
            {"TK", "TKL"},
            {"TM", "TKM"},
            {"TL", "TLS"},
            {"TO", "TON"},
            {"TT", "TTO"},
            {"TN", "TUN"},
            {"TR", "TUR"},
            {"TV", "TUV"},
            {"TW", "TWN"},
            {"TZ", "TZA"},
            {"UG", "UGA"},
            {"UA", "UKR"},
            {"UM", "UMI"},
            {"UY", "URY"},
            {"US", "USA"},
            {"UZ", "UZB"},
            {"VA", "VAT"},
            {"VC", "VCT"},
            {"VE", "VEN"},
            {"VG", "VGB"},
            {"VI", "VIR"},
            {"VN", "VNM"},
            {"VU", "VUT"},
            {"WF", "WLF"},
            {"WS", "WSM"},
            {"YE", "YEM"},
            {"ZA", "ZAF"},
            {"ZM", "ZMB"},
            {"ZW", "ZWE"}
        };
        #endregion
        #region Iso3ToIso2
        private static readonly Dictionary<string, string> Iso3ToIso2Dict = new Dictionary<string, string>();
        #endregion
        #region CountryDetector
        private static readonly Dictionary<string, string> CountryDetector = new Dictionary<string, string>
        {
            {"VIETNAM", "VNM"},
            {"SOUTH KOREA", "KOR"},
            {"EUROPEAN MONETARY UNION", "EUR"},
            {"UNITES STATES", "USA"},
            {"HONG KONG SAR", "HKG"}
        };
        #endregion
        
        static CountryManager()
        {
            foreach (var (iso3, name) in EnglishNames)
                CountryDetector.Add(name.ToUpperInvariant(), iso3);

            foreach (var (iso2, iso3) in Iso2ToIso3Dict)
            {
                Iso3ToIso2Dict.Add(iso3, iso2);
            }
        }
        
        public static string Iso2ToIso3(this string iso2)
        {
            return Iso2ToIso3Dict.ContainsKey(iso2) 
                ? Iso2ToIso3Dict[iso2] 
                : null;
        }
        
        public static string GetCountryName(this string countryCodeOrPhrase)
        {
            if (string.IsNullOrEmpty(countryCodeOrPhrase))
                return null;
            
            countryCodeOrPhrase = countryCodeOrPhrase.ToUpperInvariant();

            if (EnglishNames.ContainsKey(countryCodeOrPhrase))
                return EnglishNames[countryCodeOrPhrase];

            if (!Iso2ToIso3Dict.ContainsKey(countryCodeOrPhrase))
                return CountryDetector.ContainsKey(countryCodeOrPhrase) ? CountryDetector[countryCodeOrPhrase] : null;
            
            var iso3 = Iso2ToIso3Dict[countryCodeOrPhrase];
            return EnglishNames[iso3];
        }

        public static IReadOnlyDictionary<string, string> GetCountries()
        {
            return EnglishNames;
        }
    }
}